apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-adminui-pipeline
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/IBM/php-s2i-openshift'
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: s2i-php-v0-16-3
      params:
        - name: MINOR_VERSION
          value: '3'
        - name: PATH_CONTEXT
          value: ./src
        - name: TLSVERIFY
          value: 'false'
        - name: IMAGE
          value: docker.io/bbalasub/adminui
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: s2i-php-v0-16-3
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
